name: "POST rename_branch"
on:
  push:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          curl -H "Authorization: bearer $GH_TOKEN" -X POST -d " \
           { \
             \"query\": \"query { viewer { login }}\" \
           } \
          " https://api.github.com/graphql
